# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

warnings_are_errors: false

env:
  global:
    - PYTORCH_VERSION="1.1.0"

r-packages:
  - logging
  - reticulate
  - jsonlite
  - R6
  - rstudioapi
  - data.table


before_script:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env
  - conda install -c pytorch pytorch-cpu torchvision-cpu
  - R CMD INSTALL .
  - R -e 'rTorch::install_pytorch(version = Sys.getenv("PYTORCH_VERSION"))'
  - R -e 'rTorch::torch_config()'

