# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: xenial
sudo: false
warnings_are_errors: false


cache:
  packages: true
  directories:
    - $HOME/.cache/pip


matrix:
  include:
    - name: "PyTorch with reticulate master"
      python: "3.6"
      env:
        - PYTORCH_VERSION="1.0.0"
      r_github_packages:
        - rstudio/reticulate

before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - R -e 'rTorch::install_pytorch(version = Sys.getenv("PYTORCH_VERSION"))'
  - R -e 'rTorch::torch_config()'
